[package]
name = "http-request-common"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
percent-encoding = "1.0.1"

[dependencies.reqwest]
git = "https://github.com/seanmonstar/reqwest.git"
