[package]
name = "boncarobot"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
hiirc = "0.4.0"
toml = "0.2"
libloading = "0.3.2"
zmq = { git = "https://github.com/erickt/rust-zmq.git" }
rustyline = "1.0.0"

[workspace]
members = ["plugins/rc", "plugins/search", "plugins/shift", "plugins/template",
           "plugins/searchfix"]

[lib]
name = "plugin_api"
path = "src/plugin_api.rs"
