[package]
name = "aarena"
version = "0.1.0"
authors = ["crumblingstatue <radiantstatue@gmail.com>"]

[dependencies]
rustyline = "*"

[dependencies.split-whitespace-rest]
git = "https://github.com/crumblingstatue/split-whitespace-rest"
